package ru.javabegin.training.web.entity;
// Generated 02.08.2019 10:21:34 by Hibernate Tools 4.3.1



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private String groupid;

    public Groups() {
    }

    public Groups(String groupid) {
       this.groupid = groupid;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }




}


