package ru.javabegin.training.web.entity;
// Generated Feb 2, 2013 10:44:22 PM by Hibernate Tools 3.2.1.GA



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private String groupid;

    public Groups() {
    }

    public Groups(String groupid) {
       this.groupid = groupid;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }




}


